{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 86,
   "id": "damaged-singles",
   "metadata": {},
   "outputs": [],
   "source": [
    "import csv\n",
    "import random\n",
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "id": "handed-sphere",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>seic_benefit</th>\n",
       "      <th>health</th>\n",
       "      <th>health_benefit</th>\n",
       "      <th>house</th>\n",
       "      <th>house_benefit</th>\n",
       "      <th>nutrition</th>\n",
       "      <th>nutrition_benefit</th>\n",
       "      <th>livelihood</th>\n",
       "      <th>livelihood_benefit</th>\n",
       "      <th>education</th>\n",
       "      <th>education_benefit</th>\n",
       "      <th>scheme1</th>\n",
       "      <th>scheme1_benefit</th>\n",
       "      <th>scheme2</th>\n",
       "      <th>scheme2_benefit</th>\n",
       "      <th>seic</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>12808</td>\n",
       "      <td>58</td>\n",
       "      <td>12375</td>\n",
       "      <td>65</td>\n",
       "      <td>49114</td>\n",
       "      <td>10</td>\n",
       "      <td>75542</td>\n",
       "      <td>10</td>\n",
       "      <td>71753</td>\n",
       "      <td>42</td>\n",
       "      <td>10831</td>\n",
       "      <td>70</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>88</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>37.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>69677</td>\n",
       "      <td>100</td>\n",
       "      <td>23933</td>\n",
       "      <td>33</td>\n",
       "      <td>79399</td>\n",
       "      <td>34</td>\n",
       "      <td>40346</td>\n",
       "      <td>98</td>\n",
       "      <td>9444</td>\n",
       "      <td>76</td>\n",
       "      <td>77409</td>\n",
       "      <td>79</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>49</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>68.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>16903</td>\n",
       "      <td>55</td>\n",
       "      <td>40284</td>\n",
       "      <td>83</td>\n",
       "      <td>28046</td>\n",
       "      <td>61</td>\n",
       "      <td>17396</td>\n",
       "      <td>81</td>\n",
       "      <td>58713</td>\n",
       "      <td>83</td>\n",
       "      <td>75508</td>\n",
       "      <td>71</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>47</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>72.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>35696</td>\n",
       "      <td>40</td>\n",
       "      <td>37356</td>\n",
       "      <td>100</td>\n",
       "      <td>38886</td>\n",
       "      <td>73</td>\n",
       "      <td>59046</td>\n",
       "      <td>42</td>\n",
       "      <td>90034</td>\n",
       "      <td>71</td>\n",
       "      <td>24346</td>\n",
       "      <td>21</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>69</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>65.2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>66507</td>\n",
       "      <td>100</td>\n",
       "      <td>70600</td>\n",
       "      <td>57</td>\n",
       "      <td>53115</td>\n",
       "      <td>65</td>\n",
       "      <td>32088</td>\n",
       "      <td>100</td>\n",
       "      <td>93251</td>\n",
       "      <td>83</td>\n",
       "      <td>70920</td>\n",
       "      <td>73</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>28</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>81.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>495</th>\n",
       "      <td>28492</td>\n",
       "      <td>84</td>\n",
       "      <td>32255</td>\n",
       "      <td>43</td>\n",
       "      <td>62966</td>\n",
       "      <td>97</td>\n",
       "      <td>16134</td>\n",
       "      <td>62</td>\n",
       "      <td>91082</td>\n",
       "      <td>43</td>\n",
       "      <td>13825</td>\n",
       "      <td>42</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>48</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>65.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>496</th>\n",
       "      <td>35573</td>\n",
       "      <td>43</td>\n",
       "      <td>25476</td>\n",
       "      <td>61</td>\n",
       "      <td>46178</td>\n",
       "      <td>52</td>\n",
       "      <td>54765</td>\n",
       "      <td>33</td>\n",
       "      <td>10648</td>\n",
       "      <td>59</td>\n",
       "      <td>52504</td>\n",
       "      <td>98</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>43</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>49.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>497</th>\n",
       "      <td>6940</td>\n",
       "      <td>76</td>\n",
       "      <td>60256</td>\n",
       "      <td>46</td>\n",
       "      <td>17900</td>\n",
       "      <td>45</td>\n",
       "      <td>75069</td>\n",
       "      <td>21</td>\n",
       "      <td>68586</td>\n",
       "      <td>44</td>\n",
       "      <td>51575</td>\n",
       "      <td>58</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>86</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>46.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>498</th>\n",
       "      <td>38873</td>\n",
       "      <td>99</td>\n",
       "      <td>40842</td>\n",
       "      <td>88</td>\n",
       "      <td>50444</td>\n",
       "      <td>94</td>\n",
       "      <td>10407</td>\n",
       "      <td>90</td>\n",
       "      <td>53710</td>\n",
       "      <td>48</td>\n",
       "      <td>60860</td>\n",
       "      <td>85</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>33</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>83.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>499</th>\n",
       "      <td>28361</td>\n",
       "      <td>32</td>\n",
       "      <td>9608</td>\n",
       "      <td>57</td>\n",
       "      <td>31522</td>\n",
       "      <td>82</td>\n",
       "      <td>21484</td>\n",
       "      <td>89</td>\n",
       "      <td>83063</td>\n",
       "      <td>66</td>\n",
       "      <td>32877</td>\n",
       "      <td>72</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>55</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>65.2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>500 rows × 16 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     seic_benefit  health  health_benefit  house  house_benefit  nutrition  \\\n",
       "0           12808      58           12375     65          49114         10   \n",
       "1           69677     100           23933     33          79399         34   \n",
       "2           16903      55           40284     83          28046         61   \n",
       "3           35696      40           37356    100          38886         73   \n",
       "4           66507     100           70600     57          53115         65   \n",
       "..            ...     ...             ...    ...            ...        ...   \n",
       "495         28492      84           32255     43          62966         97   \n",
       "496         35573      43           25476     61          46178         52   \n",
       "497          6940      76           60256     46          17900         45   \n",
       "498         38873      99           40842     88          50444         94   \n",
       "499         28361      32            9608     57          31522         82   \n",
       "\n",
       "     nutrition_benefit  livelihood  livelihood_benefit  education  \\\n",
       "0                75542          10               71753         42   \n",
       "1                40346          98                9444         76   \n",
       "2                17396          81               58713         83   \n",
       "3                59046          42               90034         71   \n",
       "4                32088         100               93251         83   \n",
       "..                 ...         ...                 ...        ...   \n",
       "495              16134          62               91082         43   \n",
       "496              54765          33               10648         59   \n",
       "497              75069          21               68586         44   \n",
       "498              10407          90               53710         48   \n",
       "499              21484          89               83063         66   \n",
       "\n",
       "     education_benefit  scheme1 scheme1_benefit  scheme2 scheme2_benefit  seic  \n",
       "0                10831       70        Eligible       88        Eligible  37.0  \n",
       "1                77409       79    Non-Eligible       49        Eligible  68.2  \n",
       "2                75508       71        Eligible       47    Non-Eligible  72.6  \n",
       "3                24346       21        Eligible       69    Non-Eligible  65.2  \n",
       "4                70920       73        Eligible       28        Eligible  81.0  \n",
       "..                 ...      ...             ...      ...             ...   ...  \n",
       "495              13825       42    Non-Eligible       48        Eligible  65.8  \n",
       "496              52504       98        Eligible       43        Eligible  49.6  \n",
       "497              51575       58        Eligible       86    Non-Eligible  46.4  \n",
       "498              60860       85        Eligible       33    Non-Eligible  83.8  \n",
       "499              32877       72    Non-Eligible       55    Non-Eligible  65.2  \n",
       "\n",
       "[500 rows x 16 columns]"
      ]
     },
     "execution_count": 87,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "stretch-little",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(500, 15)"
      ]
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "seic_benefit_list = []\n",
    "\n",
    "health_list = []\n",
    "health_benefit_list = []\n",
    "\n",
    "house_list = []\n",
    "house_benefit_list =[]\n",
    "\n",
    "nutrition_list = []\n",
    "nutrition_benefit_list = []\n",
    "\n",
    "livelihood_list = []\n",
    "livelihood_benefit_list = []\n",
    "\n",
    "education_list= []\n",
    "education_benefit_list = []\n",
    "\n",
    "scheme1_list = []\n",
    "scheme1_benefit_list = []\n",
    "\n",
    "scheme2_list =[]\n",
    "scheme2_benefit_list = []\n",
    "\n",
    "scheme_choice = [\"Eligible\" , \"Non-Eligible\"]\n",
    "\n",
    "for i in range(0,500):\n",
    "    seic_benefit = random.randint(0,100000)\n",
    "    seic_benefit_list.append(seic_benefit)\n",
    "    \n",
    "    health = random.randint(20,100)\n",
    "    health_list.append(health)\n",
    "    \n",
    "    health_benefit = random.randint(0,80000)\n",
    "    health_benefit_list.append(health_benefit)\n",
    "    \n",
    "    house = random.randint(30,100)\n",
    "    house_list.append(house)\n",
    "    \n",
    "    house_benefit = random.randint(5000,80000)\n",
    "    house_benefit_list.append(house_benefit)\n",
    "    \n",
    "    \n",
    "    nutrition = random.randint(10,100)\n",
    "    nutrition_list.append(nutrition)\n",
    "    \n",
    "    \n",
    "    nutrition_benefit = random.randint(9000,80000)\n",
    "    nutrition_benefit_list.append(nutrition_benefit)\n",
    "    \n",
    "    \n",
    "    livelihood = random.randint(0,100)\n",
    "    livelihood_list.append(livelihood)\n",
    "    \n",
    "    livelihood_benefit = random.randint(0,100000)\n",
    "    livelihood_benefit_list.append(livelihood_benefit)\n",
    "\n",
    "    \n",
    "    education = random.randint(40,100)\n",
    "    education_list.append(education)\n",
    "    \n",
    "    education_benefit= random.randint(0,80000)\n",
    "    education_benefit_list.append(education_benefit)\n",
    "    \n",
    "    \n",
    "    scheme1 = random.randint(20,100)\n",
    "    scheme1_list.append(scheme1)\n",
    "    \n",
    "    scheme1_benefit = random.choice(scheme_choice)\n",
    "    scheme1_benefit_list.append(scheme1_benefit)\n",
    "    \n",
    "    scheme2=  random.randint(10,100)\n",
    "    scheme2_list.append(scheme2)\n",
    "\n",
    "    scheme2_benefit= random.choice(scheme_choice)\n",
    "    scheme2_benefit_list.append(scheme2_benefit)\n",
    "    \n",
    "    \n",
    "dict = { \"seic_benefit\" : seic_benefit_list,\n",
    "        \"health\" :health_list ,\n",
    "        \"health_benefit\" : health_benefit_list,\n",
    "       \"house\": house_list,\n",
    "       \"house_benefit\" : house_benefit_list,\n",
    "       \"nutrition\" : nutrition_list,\n",
    "        \"nutrition_benefit\" :nutrition_benefit_list,\n",
    "        \"livelihood\": livelihood_list,\n",
    "        \"livelihood_benefit\" : livelihood_benefit_list,\n",
    "        \"education\" : education_list,\n",
    "        \"education_benefit\" : education_benefit_list,\n",
    "        \"scheme1\" : scheme1_list,\n",
    "        \"scheme1_benefit\" : scheme1_benefit_list,\n",
    "        \"scheme2\" : scheme2_list,\n",
    "        \"scheme2_benefit\" : scheme2_benefit_list\n",
    "       }\n",
    "\n",
    "df = pd.DataFrame(dict)\n",
    "\n",
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "id": "intense-newsletter",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 89,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "seic = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    seic[i] = ((health_list[i] + house_list[i] + nutrition_list[i] + livelihood_list[i] + education_list[i] )/5)\n",
    "    \n",
    "len(seic)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "id": "found-leisure",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"seic\"] = seic\n",
    "\n",
    "len(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "id": "recorded-television",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>seic_benefit</th>\n",
       "      <th>health</th>\n",
       "      <th>health_benefit</th>\n",
       "      <th>house</th>\n",
       "      <th>house_benefit</th>\n",
       "      <th>nutrition</th>\n",
       "      <th>nutrition_benefit</th>\n",
       "      <th>livelihood</th>\n",
       "      <th>livelihood_benefit</th>\n",
       "      <th>education</th>\n",
       "      <th>education_benefit</th>\n",
       "      <th>scheme1</th>\n",
       "      <th>scheme1_benefit</th>\n",
       "      <th>scheme2</th>\n",
       "      <th>scheme2_benefit</th>\n",
       "      <th>seic</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>86072</td>\n",
       "      <td>89</td>\n",
       "      <td>73165</td>\n",
       "      <td>42</td>\n",
       "      <td>71830</td>\n",
       "      <td>34</td>\n",
       "      <td>39751</td>\n",
       "      <td>98</td>\n",
       "      <td>46686</td>\n",
       "      <td>51</td>\n",
       "      <td>70891</td>\n",
       "      <td>53</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>43</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>62.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>75920</td>\n",
       "      <td>44</td>\n",
       "      <td>8676</td>\n",
       "      <td>71</td>\n",
       "      <td>54466</td>\n",
       "      <td>57</td>\n",
       "      <td>45360</td>\n",
       "      <td>97</td>\n",
       "      <td>60792</td>\n",
       "      <td>61</td>\n",
       "      <td>78283</td>\n",
       "      <td>52</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>95</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>66.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>22970</td>\n",
       "      <td>95</td>\n",
       "      <td>17161</td>\n",
       "      <td>100</td>\n",
       "      <td>51961</td>\n",
       "      <td>69</td>\n",
       "      <td>32700</td>\n",
       "      <td>36</td>\n",
       "      <td>87986</td>\n",
       "      <td>63</td>\n",
       "      <td>31900</td>\n",
       "      <td>36</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>18</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>72.6</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8706</td>\n",
       "      <td>81</td>\n",
       "      <td>70125</td>\n",
       "      <td>68</td>\n",
       "      <td>26409</td>\n",
       "      <td>54</td>\n",
       "      <td>72371</td>\n",
       "      <td>59</td>\n",
       "      <td>98138</td>\n",
       "      <td>40</td>\n",
       "      <td>5130</td>\n",
       "      <td>57</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>40</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>60.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>26059</td>\n",
       "      <td>67</td>\n",
       "      <td>54973</td>\n",
       "      <td>42</td>\n",
       "      <td>37282</td>\n",
       "      <td>55</td>\n",
       "      <td>45790</td>\n",
       "      <td>80</td>\n",
       "      <td>42652</td>\n",
       "      <td>80</td>\n",
       "      <td>6901</td>\n",
       "      <td>20</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>32</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>64.8</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   seic_benefit  health  health_benefit  house  house_benefit  nutrition  \\\n",
       "0         86072      89           73165     42          71830         34   \n",
       "1         75920      44            8676     71          54466         57   \n",
       "2         22970      95           17161    100          51961         69   \n",
       "3          8706      81           70125     68          26409         54   \n",
       "4         26059      67           54973     42          37282         55   \n",
       "\n",
       "   nutrition_benefit  livelihood  livelihood_benefit  education  \\\n",
       "0              39751          98               46686         51   \n",
       "1              45360          97               60792         61   \n",
       "2              32700          36               87986         63   \n",
       "3              72371          59               98138         40   \n",
       "4              45790          80               42652         80   \n",
       "\n",
       "   education_benefit  scheme1 scheme1_benefit  scheme2 scheme2_benefit  seic  \n",
       "0              70891       53        Eligible       43        Eligible  62.8  \n",
       "1              78283       52    Non-Eligible       95    Non-Eligible  66.0  \n",
       "2              31900       36        Eligible       18    Non-Eligible  72.6  \n",
       "3               5130       57        Eligible       40        Eligible  60.4  \n",
       "4               6901       20        Eligible       32        Eligible  64.8  "
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "id": "tribal-treasury",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 110,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "seic_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.seic[i] >=70) & (df.seic_benefit[i] >=50000)):\n",
    "        seic_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.seic[i] >=70) & (df.seic_benefit[i] <=20000)):\n",
    "        seic_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.seic[i] <=30) & (df.seic_benefit[i] >=50000)):\n",
    "        seic_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.seic[i] <=30) & (df.seic_benefit[i] <=20000)):\n",
    "        seic_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        seic_error[i] = \"No Error\"\n",
    "    \n",
    "\n",
    "\n",
    "df[\"SEIC ERROR\"] = seic_error\n",
    "\n",
    "len(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 111,
   "id": "parallel-california",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 111,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "health_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.health[i] >=75) & (df.health_benefit[i] >=40000)):\n",
    "        health_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.health[i] >=75) & (df.health_benefit[i] <=10000)):\n",
    "        health_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.health[i] <=25) & (df.health_benefit[i] >=40000)):\n",
    "        health_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.health[i] <=25) & (df.health_benefit[i] <=10000)):\n",
    "        health_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        health_error[i] = \"No Error\"\n",
    "        \n",
    "df[\"Health ERROR\"] = health_error\n",
    "len(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 113,
   "id": "heated-natural",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 113,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "housing_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.house[i] >=75) & (df.house_benefit[i] >=40000)):\n",
    "        housing_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.house[i] >=75) & (df.house_benefit[i] <=10000)):\n",
    "        housing_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.house[i] <=25) & (df.house_benefit[i] >=40000)):\n",
    "        housing_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.house[i] <=25) & (df.house_benefit[i] <=10000)):\n",
    "        housing_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        housing_error[i] = \"No Error\"\n",
    "        \n",
    "df[\"House ERROR\"] = housing_error\n",
    "len(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 116,
   "id": "remarkable-forge",
   "metadata": {},
   "outputs": [],
   "source": [
    "nutrition_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.nutrition[i] >=75) & (df.nutrition_benefit[i] >=40000)):\n",
    "        nutrition_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.nutrition[i] >=75) & (df.nutrition_benefit[i] <=10000)):\n",
    "        nutrition_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.nutrition[i] <=25) & (df.nutrition_benefit[i] >=40000)):\n",
    "        nutrition_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.nutrition[i] <=25) & (df.nutrition_benefit[i] <=10000)):\n",
    "        nutrition_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        nutrition_error[i] = \"No Error\"\n",
    "        \n",
    "df[\"Nutrition ERROR\"] = nutrition_error\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 121,
   "id": "nonprofit-superior",
   "metadata": {},
   "outputs": [],
   "source": [
    "livelihood_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.livelihood[i] >=75) & (df.livelihood_benefit[i] >=40000)):\n",
    "        livelihood_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.livelihood[i] >=75) & (df.livelihood_benefit[i] <=10000)):\n",
    "        livelihood_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.livelihood[i] <=25) & (df.livelihood_benefit[i] >=40000)):\n",
    "        livelihood_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.livelihood[i] <=25) & (df.livelihood_benefit[i] <=10000)):\n",
    "        livelihood_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        livelihood_error[i] = \"No Error\"\n",
    "        \n",
    "\n",
    "df[\"livelihood ERROR\"] = livelihood_error\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 122,
   "id": "acute-simon",
   "metadata": {},
   "outputs": [],
   "source": [
    "education_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.education[i] >=75) & (df.education_benefit[i] >=40000)):\n",
    "        education_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.education[i] >=75) & (df.education_benefit[i] <=10000)):\n",
    "        education_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.education[i] <=25) & (df.education_benefit[i] >=40000)):\n",
    "        education_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.education[i] <=25) & (df.education_benefit[i] <=10000)):\n",
    "        education_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        education_error[i] = \"No Error\"\n",
    "        \n",
    "\n",
    "df[\"Education ERROR\"] = education_error"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 125,
   "id": "worldwide-logan",
   "metadata": {},
   "outputs": [],
   "source": [
    "scheme1_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.scheme1[i] >=80) & (df.scheme1_benefit[i] == \"Eligible\")):\n",
    "        scheme1_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.scheme1[i] >=80) & (df.scheme1_benefit[i] == \"Non-Eligible\")):\n",
    "        scheme1_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.scheme1[i] <=20) & (df.scheme1_benefit[i] == \"Eligible\")):\n",
    "        scheme1_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.scheme1[i] <=20) & (df.scheme1_benefit[i] == \"Non-Eligible\")):\n",
    "        scheme1_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        scheme1_error[i] = \"No Error\"\n",
    "        \n",
    "\n",
    "df[\"Scheme-1 ERROR\"] = scheme1_error\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "id": "experimental-pioneer",
   "metadata": {},
   "outputs": [],
   "source": [
    "scheme2_error = list(range(500))\n",
    "\n",
    "for i in range(500):\n",
    "    if ((df.scheme2[i] >=80) & (df.scheme2_benefit[i] == \"Eligible\")):\n",
    "        scheme2_error[i] = \"No Error\"\n",
    "        \n",
    "    elif ((df.scheme2[i] >=80) & (df.scheme2_benefit[i] == \"Non-Eligible\")):\n",
    "        scheme2_error[i] = \"EOE\"\n",
    "        \n",
    "    elif ((df.scheme2[i] <=20) & (df.scheme2_benefit[i] == \"Eligible\")):\n",
    "        scheme2_error[i] = \"EOI\"\n",
    "        \n",
    "    elif ((df.scheme2[i] <=20) & (df.scheme2_benefit[i] == \"Non-Eligible\")):\n",
    "        scheme2_error[i] = \"No Error\"\n",
    "        \n",
    "    else:\n",
    "        scheme2_error[i] = \"No Error\"\n",
    "        \n",
    "\n",
    "df[\"Scheme-2 ERROR\"] = scheme2_error\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 132,
   "id": "figured-shirt",
   "metadata": {},
   "outputs": [],
   "source": [
    "#rearranging column names\n",
    "\n",
    "df = df[[\"seic\",\"seic_benefit\",\"SEIC ERROR\",\"health\",\"health_benefit\",\"Health ERROR\",\n",
    "\"house\",\"house_benefit\" ,\"House ERROR\",\n",
    "\"nutrition\",\"nutrition_benefit\", \"Nutrition ERROR\",\n",
    "\"livelihood\",\"livelihood_benefit\" , \"livelihood ERROR\",\n",
    "\"education\",\"education_benefit\" , \"Education ERROR\",\n",
    "\"scheme1\",\"scheme1_benefit\",\"Scheme-1 ERROR\",\n",
    "\"scheme2\",\"scheme2_benefit\",\"Scheme-2 ERROR\"]]\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 133,
   "id": "derived-department",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.to_csv(\"random5.csv\",index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 134,
   "id": "billion-showcase",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "500"
      ]
     },
     "execution_count": 134,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2 = pd.read_csv(\"random5.csv\")\n",
    "len(df2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 135,
   "id": "homeless-harrison",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>seic</th>\n",
       "      <th>seic_benefit</th>\n",
       "      <th>SEIC ERROR</th>\n",
       "      <th>health</th>\n",
       "      <th>health_benefit</th>\n",
       "      <th>Health ERROR</th>\n",
       "      <th>house</th>\n",
       "      <th>house_benefit</th>\n",
       "      <th>House ERROR</th>\n",
       "      <th>nutrition</th>\n",
       "      <th>...</th>\n",
       "      <th>livelihood ERROR</th>\n",
       "      <th>education</th>\n",
       "      <th>education_benefit</th>\n",
       "      <th>Education ERROR</th>\n",
       "      <th>scheme1</th>\n",
       "      <th>scheme1_benefit</th>\n",
       "      <th>Scheme-1 ERROR</th>\n",
       "      <th>scheme2</th>\n",
       "      <th>scheme2_benefit</th>\n",
       "      <th>Scheme-2 ERROR</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>62.8</td>\n",
       "      <td>86072</td>\n",
       "      <td>No Error</td>\n",
       "      <td>89</td>\n",
       "      <td>73165</td>\n",
       "      <td>No Error</td>\n",
       "      <td>42</td>\n",
       "      <td>71830</td>\n",
       "      <td>No Error</td>\n",
       "      <td>34</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>51</td>\n",
       "      <td>70891</td>\n",
       "      <td>No Error</td>\n",
       "      <td>53</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>43</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>66.0</td>\n",
       "      <td>75920</td>\n",
       "      <td>No Error</td>\n",
       "      <td>44</td>\n",
       "      <td>8676</td>\n",
       "      <td>No Error</td>\n",
       "      <td>71</td>\n",
       "      <td>54466</td>\n",
       "      <td>No Error</td>\n",
       "      <td>57</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>61</td>\n",
       "      <td>78283</td>\n",
       "      <td>No Error</td>\n",
       "      <td>52</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>95</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>EOE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>72.6</td>\n",
       "      <td>22970</td>\n",
       "      <td>No Error</td>\n",
       "      <td>95</td>\n",
       "      <td>17161</td>\n",
       "      <td>No Error</td>\n",
       "      <td>100</td>\n",
       "      <td>51961</td>\n",
       "      <td>No Error</td>\n",
       "      <td>69</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>63</td>\n",
       "      <td>31900</td>\n",
       "      <td>No Error</td>\n",
       "      <td>36</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>18</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>60.4</td>\n",
       "      <td>8706</td>\n",
       "      <td>No Error</td>\n",
       "      <td>81</td>\n",
       "      <td>70125</td>\n",
       "      <td>No Error</td>\n",
       "      <td>68</td>\n",
       "      <td>26409</td>\n",
       "      <td>No Error</td>\n",
       "      <td>54</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>40</td>\n",
       "      <td>5130</td>\n",
       "      <td>No Error</td>\n",
       "      <td>57</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>40</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>64.8</td>\n",
       "      <td>26059</td>\n",
       "      <td>No Error</td>\n",
       "      <td>67</td>\n",
       "      <td>54973</td>\n",
       "      <td>No Error</td>\n",
       "      <td>42</td>\n",
       "      <td>37282</td>\n",
       "      <td>No Error</td>\n",
       "      <td>55</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>80</td>\n",
       "      <td>6901</td>\n",
       "      <td>EOE</td>\n",
       "      <td>20</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>EOI</td>\n",
       "      <td>32</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>495</th>\n",
       "      <td>48.6</td>\n",
       "      <td>98742</td>\n",
       "      <td>No Error</td>\n",
       "      <td>74</td>\n",
       "      <td>72806</td>\n",
       "      <td>No Error</td>\n",
       "      <td>36</td>\n",
       "      <td>21046</td>\n",
       "      <td>No Error</td>\n",
       "      <td>48</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>64</td>\n",
       "      <td>22496</td>\n",
       "      <td>No Error</td>\n",
       "      <td>80</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>EOE</td>\n",
       "      <td>88</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>EOE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>496</th>\n",
       "      <td>59.8</td>\n",
       "      <td>59864</td>\n",
       "      <td>No Error</td>\n",
       "      <td>23</td>\n",
       "      <td>8550</td>\n",
       "      <td>No Error</td>\n",
       "      <td>43</td>\n",
       "      <td>39556</td>\n",
       "      <td>No Error</td>\n",
       "      <td>63</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>79</td>\n",
       "      <td>54764</td>\n",
       "      <td>No Error</td>\n",
       "      <td>38</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>15</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>EOI</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>497</th>\n",
       "      <td>59.8</td>\n",
       "      <td>57695</td>\n",
       "      <td>No Error</td>\n",
       "      <td>46</td>\n",
       "      <td>27416</td>\n",
       "      <td>No Error</td>\n",
       "      <td>78</td>\n",
       "      <td>53691</td>\n",
       "      <td>No Error</td>\n",
       "      <td>46</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>98</td>\n",
       "      <td>78011</td>\n",
       "      <td>No Error</td>\n",
       "      <td>38</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>34</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>498</th>\n",
       "      <td>56.4</td>\n",
       "      <td>73539</td>\n",
       "      <td>No Error</td>\n",
       "      <td>60</td>\n",
       "      <td>79211</td>\n",
       "      <td>No Error</td>\n",
       "      <td>39</td>\n",
       "      <td>71169</td>\n",
       "      <td>No Error</td>\n",
       "      <td>52</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>56</td>\n",
       "      <td>40690</td>\n",
       "      <td>No Error</td>\n",
       "      <td>25</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>19</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>499</th>\n",
       "      <td>48.6</td>\n",
       "      <td>14679</td>\n",
       "      <td>No Error</td>\n",
       "      <td>24</td>\n",
       "      <td>16078</td>\n",
       "      <td>No Error</td>\n",
       "      <td>93</td>\n",
       "      <td>29750</td>\n",
       "      <td>No Error</td>\n",
       "      <td>12</td>\n",
       "      <td>...</td>\n",
       "      <td>No Error</td>\n",
       "      <td>44</td>\n",
       "      <td>15183</td>\n",
       "      <td>No Error</td>\n",
       "      <td>20</td>\n",
       "      <td>Non-Eligible</td>\n",
       "      <td>No Error</td>\n",
       "      <td>51</td>\n",
       "      <td>Eligible</td>\n",
       "      <td>No Error</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>500 rows × 24 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "     seic  seic_benefit SEIC ERROR  health  health_benefit Health ERROR  \\\n",
       "0    62.8         86072   No Error      89           73165     No Error   \n",
       "1    66.0         75920   No Error      44            8676     No Error   \n",
       "2    72.6         22970   No Error      95           17161     No Error   \n",
       "3    60.4          8706   No Error      81           70125     No Error   \n",
       "4    64.8         26059   No Error      67           54973     No Error   \n",
       "..    ...           ...        ...     ...             ...          ...   \n",
       "495  48.6         98742   No Error      74           72806     No Error   \n",
       "496  59.8         59864   No Error      23            8550     No Error   \n",
       "497  59.8         57695   No Error      46           27416     No Error   \n",
       "498  56.4         73539   No Error      60           79211     No Error   \n",
       "499  48.6         14679   No Error      24           16078     No Error   \n",
       "\n",
       "     house  house_benefit House ERROR  nutrition  ...  livelihood ERROR  \\\n",
       "0       42          71830    No Error         34  ...          No Error   \n",
       "1       71          54466    No Error         57  ...          No Error   \n",
       "2      100          51961    No Error         69  ...          No Error   \n",
       "3       68          26409    No Error         54  ...          No Error   \n",
       "4       42          37282    No Error         55  ...          No Error   \n",
       "..     ...            ...         ...        ...  ...               ...   \n",
       "495     36          21046    No Error         48  ...          No Error   \n",
       "496     43          39556    No Error         63  ...          No Error   \n",
       "497     78          53691    No Error         46  ...          No Error   \n",
       "498     39          71169    No Error         52  ...          No Error   \n",
       "499     93          29750    No Error         12  ...          No Error   \n",
       "\n",
       "    education  education_benefit  Education ERROR scheme1  scheme1_benefit  \\\n",
       "0          51              70891         No Error      53         Eligible   \n",
       "1          61              78283         No Error      52     Non-Eligible   \n",
       "2          63              31900         No Error      36         Eligible   \n",
       "3          40               5130         No Error      57         Eligible   \n",
       "4          80               6901              EOE      20         Eligible   \n",
       "..        ...                ...              ...     ...              ...   \n",
       "495        64              22496         No Error      80     Non-Eligible   \n",
       "496        79              54764         No Error      38         Eligible   \n",
       "497        98              78011         No Error      38         Eligible   \n",
       "498        56              40690         No Error      25     Non-Eligible   \n",
       "499        44              15183         No Error      20     Non-Eligible   \n",
       "\n",
       "     Scheme-1 ERROR scheme2  scheme2_benefit Scheme-2 ERROR  \n",
       "0          No Error      43         Eligible       No Error  \n",
       "1          No Error      95     Non-Eligible            EOE  \n",
       "2          No Error      18     Non-Eligible       No Error  \n",
       "3          No Error      40         Eligible       No Error  \n",
       "4               EOI      32         Eligible       No Error  \n",
       "..              ...     ...              ...            ...  \n",
       "495             EOE      88     Non-Eligible            EOE  \n",
       "496        No Error      15         Eligible            EOI  \n",
       "497        No Error      34         Eligible       No Error  \n",
       "498        No Error      19     Non-Eligible       No Error  \n",
       "499        No Error      51         Eligible       No Error  \n",
       "\n",
       "[500 rows x 24 columns]"
      ]
     },
     "execution_count": 135,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "incomplete-sailing",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
